---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/.env
  entrypoint:
    - /bin/bash
    - -c
    - |
      
      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=WEB3,ETH,NET,TRACE \
      --rpc-ws-api=WEB3,ETH,NET,TRACE;
services:
  rpc:
    << : *besu-def
    container_name: rpc1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Staging-RPC-1,service.version=${BESU_VERSION:-latest}
      - BESU_ETHSTATS=Staging-RPC-1:${ETHSTAT_SECRET}@${ETHSTAT_URL_AND_PORT}
      - BESU_ETHSTATS_CONTACT=${NODE_ADMIN_EMAIL}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/:/config
      - ./node_files/rpc1/keys:/opt/besu/keys
      - ./node_files/rpc1/tls:/opt/besu/tls
      - ./node_files/rpc1/tls/trusted:/opt/besu/tls/trusted
      - ./node_files/rpc1/logs:/tmp/besu
      - ./node_files/rpc1/data:/opt/besu/data
    networks:
      camdl-staging-network:
        ipv4_address: 172.16.239.21
  validator1:
    << : *besu-def
    container_name: validator1
    ports:
      - 21001:8545/tcp
      - 31001:8546/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Staging-Validator-1,service.version=${BESU_VERSION:-latest}
      - BESU_ETHSTATS=Staging-Validator-1:${ETHSTAT_SECRET}@${ETHSTAT_URL_AND_PORT}
      - BESU_ETHSTATS_CONTACT=${NODE_ADMIN_EMAIL}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/:/config
      - ./node_files/validator1/keys:/opt/besu/keys
      - ./node_files/validator1/tls:/opt/besu/tls
      - ./node_files/validator1/tls/trusted:/opt/besu/tls/trusted
      - ./node_files/validator1/logs:/tmp/besu
      - ./node_files/validator1/data:/opt/besu/data
    networks:
      camdl-staging-network:
        ipv4_address: 172.16.239.11
  validator2:
    << : *besu-def
    container_name: validator2
    ports:
      - 21002:8545/tcp
      - 31002:8546/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Staging-Validator-2,service.version=${BESU_VERSION:-latest}
      - BESU_ETHSTATS=Staging-Validator-2:${ETHSTAT_SECRET}@${ETHSTAT_URL_AND_PORT}
      - BESU_ETHSTATS_CONTACT=${NODE_ADMIN_EMAIL}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/:/config
      - ./node_files/validator2/keys:/opt/besu/keys
      - ./node_files/validator2/tls:/opt/besu/tls
      - ./node_files/validator2/tls/trusted:/opt/besu/tls/trusted
      - ./node_files/validator2/logs:/tmp/besu
      - ./node_files/validator2/data:/opt/besu/data
    networks:
      camdl-staging-network:
        ipv4_address: 172.16.239.12
  validator3:
    << : *besu-def
    container_name: validator3
    ports:
      - 21003:8545/tcp
      - 31003:8546/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Staging-Validator-3,service.version=${BESU_VERSION:-latest}
      - BESU_ETHSTATS=Staging-Validator-3:${ETHSTAT_SECRET}@${ETHSTAT_URL_AND_PORT}
      - BESU_ETHSTATS_CONTACT=${NODE_ADMIN_EMAIL}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/:/config
      - ./node_files/validator3/keys:/opt/besu/keys
      - ./node_files/validator3/tls:/opt/besu/tls
      - ./node_files/validator3/tls/trusted:/opt/besu/tls/trusted
      - ./node_files/validator3/logs:/tmp/besu
      - ./node_files/validator3/data:/opt/besu/data
    networks:
      camdl-staging-network:
        ipv4_address: 172.16.239.13
  validator4:
    << : *besu-def
    container_name: validator4
    ports:
      - 21004:8545/tcp
      - 31004:8546/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=Staging-Validator-4,service.version=${BESU_VERSION:-latest}
      - BESU_ETHSTATS=Staging-Validator-4:${ETHSTAT_SECRET}@${ETHSTAT_URL_AND_PORT}
      - BESU_ETHSTATS_CONTACT=${NODE_ADMIN_EMAIL}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/:/config
      - ./node_files/validator4/keys:/opt/besu/keys
      - ./node_files/validator4/tls:/opt/besu/tls
      - ./node_files/validator4/tls/trusted:/opt/besu/tls/trusted
      - ./node_files/validator4/logs:/tmp/besu
      - ./node_files/validator4/data:/opt/besu/data
    networks:
      camdl-staging-network:
        ipv4_address: 172.16.239.14
networks:
  camdl-staging-network:
    name: camdl-staging-network
    ipam:
      config:
        - subnet: 172.16.239.0/24